on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
  BUCKET_NAME: caarels-artifacts
jobs:
  awscli-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: aws --version
    - run: aws sts get-caller-identity
    - run: mkdir artifacts
    - run: cd artifacts
    - run: dd if=/dev/zero of=dummy.file bs=1024 count=10240
    - run: pwd
    - run: ls -lah