on: [push]

jobs:
  awscli-job:
    runs-on: ubuntu-latest
    name: AWS test jobs
    steps:
    - name: Get caller identity
      id: awscli
      uses: martyca/mytestaction@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}