on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
jobs:
  awscli-job:
    runs-on: ubuntu-latest
    steps:
    - run: aws --version
    - run: aws sts get-caller-identity