on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    env:
      FOO: ${{ secrets.SECRET_FOO }}

    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: martyca/mytestaction@master
      env:
        BAR: ${{ secrets.SECRET_FOO }}
      with:
        greeter: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"