on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
  BUCKET_NAME: caarels-artifacts
jobs:
  awscli-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: aws --version
    - run: aws sts get-caller-identity
    - run: mkdir -p ./artifacts
    - run: dd if=/dev/zero of=dummy.file bs=1024 count=10240
      working-directory: artifacts 
    - run: pwd
      working-directory: artifacts
    - run: tree
    - run: echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2
    - run: echo ${REPO_NAME}
    - run: aws s3 cp ./dummy.file s3://${BUCKET_NAME}/$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)/
      working-directory: artifacts 
